language: php
os: linux

branches:
    only:
        - master
        - 3.x

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.2
    - 7.3
    - 7.4

before_install:
    - composer self-update

install:
    - COMPOSER_MEMORY_LIMIT=-1 composer update $COMPOSER_FLAGS --prefer-dist

before_script:
    - phpenv config-rm xdebug.ini
    - pecl install pcov

script:
    - if [ $(phpenv version-name) = "7.2" ]; then ./vendor/bin/phpunit --disable-coverage; fi
    - if [ $(phpenv version-name) = "7.3" ]; then ./vendor/bin/phpunit --disable-coverage; fi
    - if [ $(phpenv version-name) = "7.4" ]; then php -d pcov.enabled=1 ./vendor/bin/phpunit --coverage-clover clover.xml; fi

after_script:
    - if [ $(phpenv version-name) = "7.4" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then bash <(curl -s https://codecov.io/bash); fi

jobs:
    fast_finish: true
