services:
  dh_doctrine_audit.annotation_loader:
    class: DH\DoctrineAuditBundle\Annotation\AnnotationLoader
    arguments: ["@doctrine.orm.default_entity_manager"]

  DH\DoctrineAuditBundle\Annotation\AnnotationLoader:
    alias: dh_doctrine_audit.annotation_loader

  dh_doctrine_audit.configuration:
    class: DH\DoctrineAuditBundle\Configuration
    arguments:
      - "%dh_doctrine_audit.configuration%"
      - "@dh_doctrine_audit.user_provider"
      - "@request_stack"
      - "@security.firewall.map"
      - "@doctrine.orm.default_entity_manager"
      - "@dh_doctrine_audit.annotation_loader"
      - "@event_dispatcher"

  DH\DoctrineAuditBundle\Configuration:
    alias: dh_doctrine_audit.configuration

  dh_doctrine_audit.reader:
    class: DH\DoctrineAuditBundle\Reader\Reader
    arguments:
      - "@dh_doctrine_audit.configuration"
      - "@doctrine.orm.default_entity_manager"
    public: true

  DH\DoctrineAuditBundle\Reader\Reader:
    alias: dh_doctrine_audit.reader
    public: true

  dh_doctrine_audit.manager:
    class: DH\DoctrineAuditBundle\Manager\TransactionManager
    arguments:
      - "@dh_doctrine_audit.configuration"
    public: true

  DH\DoctrineAuditBundle\Manager\TransactionManager:
    alias: dh_doctrine_audit.manager
    public: true

  dh_doctrine_audit.user_provider:
    class: DH\DoctrineAuditBundle\User\TokenStorageUserProvider
    arguments: ["@security.helper"]

  dh_doctrine_audit.twig_extension:
    class: DH\DoctrineAuditBundle\Twig\Extension\TwigExtension
    arguments: ['@doctrine']
    tags:
      - { name: twig.extension }

  dh_doctrine_audit.event_subscriber.audit:
    class: DH\DoctrineAuditBundle\Event\AuditSubscriber
    arguments: ["@dh_doctrine_audit.manager"]
    tags:
      - { name: kernel.event_subscriber }

  dh_doctrine_audit.event_subscriber.doctrine:
    class: DH\DoctrineAuditBundle\Event\DoctrineSubscriber
    arguments: ["@dh_doctrine_audit.manager"]
    tags:
      - { name: doctrine.event_subscriber, priority: 1000000 }

  dh_doctrine_audit.event_subscriber.create_schema:
    class: DH\DoctrineAuditBundle\Event\CreateSchemaListener
    arguments: ["@dh_doctrine_audit.manager", "@dh_doctrine_audit.reader"]
    tags:
      - { name: doctrine.event_subscriber }

  dh_doctrine_audit.command.clean:
    class: DH\DoctrineAuditBundle\Command\CleanAuditLogsCommand
    tags:
      - { name: 'console.command', command: 'audit:clean' }

  DH\DoctrineAuditBundle\Command\CleanAuditLogsCommand:
    alias: dh_doctrine_audit.command.clean

  dh_doctrine_audit.command.schema_update:
    class: DH\DoctrineAuditBundle\Command\UpdateSchemaCommand
    tags:
      - { name: 'console.command', command: 'audit:schema:update' }

  DH\DoctrineAuditBundle\Command\UpdateSchemaCommand:
    alias: dh_doctrine_audit.command.schema_update

  DH\DoctrineAuditBundle\Controller\ViewerController:
    calls:
      - { method: setContainer, arguments: ['@service_container'] }
    tags: ['controller.service_arguments']

  DH\DoctrineAuditBundle\Routing\RoutingAnnotationLoader:
    tags: [routing.loader]
    arguments:
      - '@routing.loader.annotation'
      - '%dh_doctrine_audit.configuration%'